In [7]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [3]:
# load data from the npz file.
training_data = np.load('processed_npz_files/data_out_psd_1074023.npz')

In [4]:
training_data['labels'].shape

(2001, 512)

In [6]:
np.unique(training_data['labels'], return_counts=True)

(array([0, 1], dtype=int8), array([1023296,    1216]))

In [8]:
x_train = training_data['Z']

In [9]:
x_train.shape

(2001, 512)

In [11]:
x_train[0].shape

(512,)

In [12]:
# model parameters.
sequence_length = 8

In [13]:
y_train = training_data['labels']

In [14]:
y = list()
for i in range(x_train.shape[0]):
    y_inner = list()
    for j in range(x_train.shape[1]-8):
        if np.count_nonzero(y_train[i, j:j+8] == 1) >= 4:
            y_inner.append(1)
        else:
            y_inner.append(0)
    y.append(np.array(y_inner, dtype=np.int8))

In [15]:
y_np = np.array(y)

In [16]:
y_np.shape

(2001, 504)

In [20]:
np.unique(y_np,return_counts=True)

(array([0, 1], dtype=int8), array([1007256,    1248]))

In [ ]:
x_train = np.reshape()

## Sequence Parameters.

In [55]:
# model parameters.
sequence_length = 8

In [38]:
x_train_rnn = np.reshape(x_train, (x_train.shape[0], sequence_length, 1))

In [39]:
x_train_rnn.shape

(2001, 512, 1)

In [45]:
y_np = np.reshape(y_np, (y_np.shape[0], 504, 1))

In [46]:
y_np.shape

(2001, 504, 1)

In [48]:
x_test = x_train[0]

In [49]:
x_test.shape

(512,)

In [51]:
x_test[:32]

array([9.1555863e-05, 3.0518622e-05, 6.1037244e-05, 6.1037244e-05,
       6.1037244e-05, 6.1037244e-05, 3.0518622e-05, 6.1037244e-05,
       9.1555863e-05, 3.0518622e-05, 3.0518622e-05, 6.1037244e-05,
       3.0518622e-05, 6.1037244e-05, 9.1555863e-05, 9.1555863e-05,
       9.1555863e-05, 3.0518622e-05, 6.1037244e-05, 6.1037244e-05,
       3.0518622e-05, 3.0518622e-05, 9.1555863e-05, 9.1555863e-05,
       1.2207449e-04, 6.1037244e-05, 6.1037244e-05, 3.0518622e-05,
       3.0518622e-05, 3.0518622e-05, 9.1555863e-05, 9.1555863e-05],
      dtype=float32)

In [52]:
x_test = np.reshape(x_test, (64, 8))

In [53]:
x_test[0]

array([9.1555863e-05, 3.0518622e-05, 6.1037244e-05, 6.1037244e-05,
       6.1037244e-05, 6.1037244e-05, 3.0518622e-05, 6.1037244e-05],
      dtype=float32)

In [54]:
x_test[1]

array([9.1555863e-05, 3.0518622e-05, 3.0518622e-05, 6.1037244e-05,
       3.0518622e-05, 6.1037244e-05, 9.1555863e-05, 9.1555863e-05],
      dtype=float32)

In [59]:
print('new expected shape')
print('x dimension ', x_train.shape[0] * (x_train.shape[1] // sequence_length))

new expected shape
x dimension  128064


In [60]:
x_train_rnn = np.reshape(x_train, (x_train.shape[0] * (x_train.shape[1] // sequence_length), sequence_length, 1) )

In [71]:
y_train_rnn = np.reshape(y_train, (x_train.shape[0] * (x_train.shape[1] // sequence_length), sequence_length))

In [80]:
x_train_rnn1 = list()
for i in range(x_train.shape[0]):
    x_train_rnn1.append(np.reshape(x_train[0], (64, 8)))
x_train_rnn1 = np.array(x_train_rnn1)

In [81]:
x_train_rnn1.shape

(2001, 64, 8)

In [87]:
print('x shape', x_train.shape)
print('y shape', y_train.shape)

x shape (2001, 512)
y shape (2001, 512)


In [140]:
def generate_sequence_data(index):
    n = x_train[index].shape[0]
    L = 8
    x_train_seq = []
    y_train_seq = []
    for k in range(n - L + 1):
        x_train_seq.append(x_train[index][k : k + L])
        y_train_seq.append(y_train[index][k : k + L])

    x_train_seq = np.array(x_train_seq)
    y_train_seq = np.array(y_train_seq)
    return x_train_seq, y_train_seq

In [151]:
xy = [generate_sequence_data(i) for i in range(x_train.shape[0])]

In [162]:
x_train_seq = list()
y_train_seq = list()
for item in xy:
    x_train_seq.append(np.reshape(item[0], (item[0].shape[0], item[0].shape[1], 1)))
    y_train_seq.append(np.reshape(item[0], (item[0].shape[0], item[0].shape[1], 1)))
    
# x_train_seq = np.array(x_train_seq)
# y_train_seq = np.array(y_train_seq)

In [164]:
print('reshaped x shape', len(x_train_seq))
print('reshaped y shape', len(y_train_seq))

reshaped x shape 2001
reshaped y shape 2001


In [132]:
x_train_seq = np.reshape(x_train_seq, (x_train_seq.shape[0], x_train_seq.shape[1], 1))
y_train_seq = np.reshape(y_train_seq, (y_train_seq.shape[0], y_train_seq.shape[1], 1))

In [165]:
print('reshaped x shape', x_train_seq[0].shape)
print('reshaped y shape', y_train_seq[0].shape)

reshaped x shape (505, 8, 1)
reshaped y shape (505, 8, 1)


## Creating the RNN model.

In [166]:
rnn = keras.models.Sequential()
rnn.add(keras.layers.LSTM(32, return_sequences=True))
rnn.add(keras.layers.Dense(1, activation='sigmoid'))

In [167]:
rnn.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adadelta(), metrics=['accuracy'])

In [168]:
for i in range(len(x_train_seq)):
    rnn.train_on_batch(x_train_seq[i], y_train_seq[i])

In [169]:
rnn.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_21 (LSTM)               (None, 8, 32)             4352      
_________________________________________________________________
dense_15 (Dense)             (None, 8, 1)              33        
Total params: 4,385
Trainable params: 4,385
Non-trainable params: 0
_________________________________________________________________


In [171]:
rnn.evaluate(x_train_seq[12], y_train_seq[12])

505/505 [==============================] - 0s 118us/step


[0.001338228274892905, 0.0]