In [1]:
import tensorflow as tf
import numpy as np

In [2]:
dataset = tf.data.TextLineDataset('file.txt')

In [ ]:
for line in dataset:
    print(line)

In [3]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [4]:
with tf.Session() as sess:
    for i in range(3):
        print(sess.run(next_element))

b'I use Tensorflow'
b'You use PyTorch'
b'Both are great'


In [5]:
dataset = dataset.map(lambda string: tf.string_split([string]).values)

In [6]:
dataset = dataset.shuffle(buffer_size=3)

In [7]:
dataset.batch(2)

<BatchDataset shapes: (?, ?), types: tf.string>

In [8]:
dataset.prefetch(1)

<PrefetchDataset shapes: (?,), types: tf.string>

In [9]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [10]:
with tf.Session() as sess:
    print(sess.run(next_element))

[b'You' b'use' b'PyTorch']


# use initalizer op.

In [13]:
dataset = tf.data.TextLineDataset("file.txt")
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()
init_op = iterator.initializer

In [14]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(next_element))
    print(sess.run(next_element))
    sess.run(init_op)
    print(sess.run(next_element))

b'I use Tensorflow'
b'You use PyTorch'
b'I use Tensorflow'


## what I need to read from the dataset.
(1950, 512) ->
each 512 line is an input
convert each 512 line into [0,...num_sequences], [i+1, ... num_sequences] => total no. of sequences should be equal to 512. - Task 1

In [91]:
freq = [i for i in range(512)]
freq = np.array(freq)

In [51]:
# freq = np.random.sample((512, 1))
# labels = np.random.randint(0, 4, (512, 1))

In [92]:
freq = freq.reshape(freq.shape[0], 1)

In [93]:
batch_size = 20
num_steps = 16

In [87]:
# convert into num step sized repeated samples.
def convertStepSizes(freq, num_steps):
    freq_reshaped = list()
    for i in range(freq.shape[0]):
        inner_array = np.array(freq[i:i+num_steps, 0])
        inner_array = np.pad(inner_array, 16-inner_array.shape[0], 'edge')
        freq_reshaped.append(inner_array)
    
    freq_reshaped = np.array(freq_reshaped)
    return freq_reshaped

In [88]:
freq = convertStepSizes(freq, 16)

In [89]:
for i in range(freq.shape[0]):
    if freq[i].shape[0] < 16:
        print(i)

In [90]:
freq[0]

array([array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
       array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
       array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
       array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
       array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
       array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
       array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
       array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]),
       array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]),
       array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]),
       array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]),
       array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]),
       array([12, 13, 14, 15, 16, 17, 18

In [73]:
freq[1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [74]:
freq[-1]

array([511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511,
       511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511,
       511, 511, 511, 511, 511])

In [75]:
freq[0].shape

(16,)

In [76]:
freq.shape

(512,)

In [24]:
dataset_freq = tf.data.Dataset.from_tensor_slices(freq)
# dataset_freq = dataset_freq.batch(16)

In [25]:
iterator = dataset_freq.make_one_shot_iterator()
next_element = iterator.get_next()

In [26]:
with tf.Session() as sess:
    print(sess.run(next_element))

[0.54867349]
